osx_image: xcode8
language: objective-c
branches:
    only:
        - master
before_install:
    - gem install xcpretty
script: xcodebuild -project STURLEncoding.xcodeproj -scheme ${XCODE_SCHEME} -sdk ${XCODE_SDK} | xcpretty
env:
    - XCODE_SCHEME=STURLEncoding-iOS XCODE_SDK=iphonesimulator
    - XCODE_SCHEME=STURLEncoding-mac XCODE_SDK=macosx
